# Generated by Django 5.1.7 on 2026-09-15 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('MATERIAL', 'Materials'), ('MACHINE', 'Machines'), ('LABOR', 'Labor Roles'), ('QUOTE_INPUT', 'Quote Inputs')], max_length=30)),
                ('uploaded_file', models.FileField(upload_to='imports/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial')], default='PENDING', max_length=20)),
                ('row_success', models.PositiveIntegerField(default=0)),
                ('row_failed', models.PositiveIntegerField(default=0)),
                ('error_summary', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('correlation_id', models.UUIDField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportRowError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('column', models.CharField(blank=True, default='', max_length=100)),
                ('message', models.TextField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row_errors', to='imports_excel.importjob')),
            ],
            options={
                'ordering': ['row_number'],
            },
        ),
    ]
