# Generated by Django 5.1.7 on 2026-09-15 08:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], db_index=True, default='INFO', max_length=20)),
                ('source', models.CharField(db_index=True, max_length=100)),
                ('event_type', models.CharField(choices=[('EXCEPTION', 'Exception'), ('IMPORT', 'Import'), ('COSTING', 'Costing'), ('PDF', 'PDF'), ('AUTH', 'Auth'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=20)),
                ('message', models.TextField()),
                ('traceback', models.TextField(blank=True, default='')),
                ('request_path', models.CharField(blank=True, default='', max_length=500)),
                ('http_method', models.CharField(blank=True, default='', max_length=10)),
                ('correlation_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'level'], name='auditlog_sy_created_ea22d3_idx'), models.Index(fields=['event_type', '-created_at'], name='auditlog_sy_event_t_717a07_idx')],
            },
        ),
    ]
