# Generated by Django 5.1.7 on 2026-09-15 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name_plural': 'product families',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ProductTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.SlugField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='templates_engine.productfamily')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_templates', to='core.plant')),
            ],
            options={
                'ordering': ['code', '-version'],
                'unique_together': {('plant', 'code', 'version')},
            },
        ),
        migrations.CreateModel(
            name='TemplateBomItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('qty_formula', models.TextField()),
                ('scrap_formula', models.TextField(default='0')),
                ('cost_group', models.CharField(choices=[('MATERIAL', 'Material'), ('PACKAGING', 'Packaging'), ('OTHER', 'Other')], default='MATERIAL', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bom_usages', to='catalog.material')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_items', to='templates_engine.producttemplate')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TemplateMarginRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('MARGIN_PERCENT', 'Margin %'), ('MARKUP_PERCENT', 'Markup %'), ('FIXED_PRICE', 'Fixed Price')], default='MARGIN_PERCENT', max_length=30)),
                ('value_or_formula', models.TextField(default='25')),
                ('template', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='margin_rule', to='templates_engine.producttemplate')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=10)),
                ('name', models.CharField(max_length=200)),
                ('setup_time_formula_min', models.TextField(default='0')),
                ('cycle_time_formula_min', models.TextField(default='0')),
                ('labor_time_formula_min', models.TextField(default='0')),
                ('notes', models.TextField(blank=True, default='')),
                ('labor_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_ops', to='catalog.laborrole')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_ops', to='catalog.machine')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='templates_engine.producttemplate')),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TemplateCostElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField()),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('OVERHEAD', 'Overhead'), ('FREIGHT', 'Freight'), ('TOOLING', 'Tooling'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('amount_formula', models.TextField()),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_elements', to='templates_engine.producttemplate')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('template', 'code')},
            },
        ),
        migrations.CreateModel(
            name='TemplateFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField()),
                ('expression', models.TextField()),
                ('return_unit', models.CharField(blank=True, default='', max_length=30)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulas', to='templates_engine.producttemplate')),
            ],
            options={
                'verbose_name_plural': 'template formulas',
                'ordering': ['sort_order', 'code'],
                'unique_together': {('template', 'code')},
            },
        ),
        migrations.CreateModel(
            name='TemplateParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField()),
                ('label', models.CharField(max_length=200)),
                ('data_type', models.CharField(choices=[('number', 'Number'), ('text', 'Text'), ('bool', 'Boolean')], default='number', max_length=20)),
                ('unit', models.CharField(blank=True, default='', max_length=30)),
                ('default_value', models.CharField(blank=True, default='', max_length=100)),
                ('min_value', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('is_required', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('help_text', models.CharField(blank=True, default='', max_length=255)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='templates_engine.producttemplate')),
            ],
            options={
                'ordering': ['sort_order', 'code'],
                'unique_together': {('template', 'code')},
            },
        ),
    ]
