# Generated by Django 5.2.17 on 2026-09-19 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('core', '0001_initial'),
        ('quotes', '0004_alter_customer_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField()),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('result_formula', models.TextField(blank=True, default='0', help_text='Expression using field codes (e.g. LENGTH * RATE). Evaluated to the process final value.')),
                ('result_unit', models.CharField(choices=[('MONEY', 'Money'), ('TIME', 'Time')], default='MONEY', max_length=10)),
                ('use_material_properties', models.BooleanField(default=False, help_text='If enabled, quote can pick a material and MAT_* properties enter the formula context.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='core.plant')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='QuoteProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('computed_own', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('computed_total', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_processes', to='catalog.material')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quote_usages', to='processes.process')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_processes', to='quotes.quote')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SubProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField()),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('result_formula', models.TextField(blank=True, default='0', help_text='Expression using field codes. Result is added into the parent process total.')),
                ('result_unit', models.CharField(choices=[('MONEY', 'Money'), ('TIME', 'Time')], default='MONEY', max_length=10)),
                ('use_material_properties', models.BooleanField(default=False, help_text='If enabled, inherits material context from the parent quote process when available.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subprocesses', to='core.plant')),
            ],
            options={
                'verbose_name': 'sub process',
                'verbose_name_plural': 'sub processes',
                'ordering': ['code'],
                'unique_together': {('plant', 'code')},
            },
        ),
        migrations.CreateModel(
            name='QuoteSubProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('computed_value', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('quote_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subprocesses', to='processes.quoteprocess')),
                ('subprocess', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quote_usages', to='processes.subprocess')),
            ],
            options={
                'verbose_name': 'quote sub process',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProcessSubProcessLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subprocess_links', to='processes.process')),
                ('subprocess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_links', to='processes.subprocess')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'unique_together': {('process', 'subprocess')},
            },
        ),
        migrations.AddField(
            model_name='process',
            name='subprocesses',
            field=models.ManyToManyField(blank=True, related_name='processes', through='processes.ProcessSubProcessLink', to='processes.subprocess'),
        ),
        migrations.CreateModel(
            name='ProcessField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField()),
                ('label', models.CharField(max_length=200)),
                ('data_type', models.CharField(choices=[('number', 'Number'), ('text', 'Text'), ('bool', 'Boolean')], default='number', max_length=20)),
                ('unit', models.CharField(blank=True, default='', max_length=30)),
                ('default_value', models.CharField(blank=True, default='', max_length=100)),
                ('min_value', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('is_required', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('help_text', models.CharField(blank=True, default='', max_length=255)),
                ('material_property_key', models.SlugField(blank=True, default='', help_text='Optional. e.g. unit_price or a custom field key. Leave blank to disable.', max_length=80)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='processes.process')),
            ],
            options={
                'ordering': ['sort_order', 'code'],
                'unique_together': {('process', 'code')},
            },
        ),
        migrations.CreateModel(
            name='QuoteProcessFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_code', models.SlugField()),
                ('value', models.CharField(blank=True, default='', max_length=200)),
                ('quote_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='processes.quoteprocess')),
            ],
            options={
                'unique_together': {('quote_process', 'field_code')},
            },
        ),
        migrations.CreateModel(
            name='QuoteSubProcessFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_code', models.SlugField()),
                ('value', models.CharField(blank=True, default='', max_length=200)),
                ('quote_subprocess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='processes.quotesubprocess')),
            ],
            options={
                'unique_together': {('quote_subprocess', 'field_code')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='process',
            unique_together={('plant', 'code')},
        ),
        migrations.CreateModel(
            name='SubProcessField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField()),
                ('label', models.CharField(max_length=200)),
                ('data_type', models.CharField(choices=[('number', 'Number'), ('text', 'Text'), ('bool', 'Boolean')], default='number', max_length=20)),
                ('unit', models.CharField(blank=True, default='', max_length=30)),
                ('default_value', models.CharField(blank=True, default='', max_length=100)),
                ('min_value', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('is_required', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('help_text', models.CharField(blank=True, default='', max_length=255)),
                ('material_property_key', models.SlugField(blank=True, default='', help_text='Optional. e.g. unit_price or a custom field key. Leave blank to disable.', max_length=80)),
                ('subprocess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='processes.subprocess')),
            ],
            options={
                'verbose_name': 'sub process field',
                'ordering': ['sort_order', 'code'],
                'unique_together': {('subprocess', 'code')},
            },
        ),
    ]
