# Generated by Django 5.2.17 on 2026-09-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='process',
            index=models.Index(fields=['is_active'], name='proc_process_is_active_idx'),
        ),
        migrations.AddIndex(
            model_name='process',
            index=models.Index(fields=['plant', 'is_active'], name='proc_process_plant_active_idx'),
        ),
        migrations.AddIndex(
            model_name='subprocess',
            index=models.Index(fields=['is_active'], name='proc_subprocess_is_active_idx'),
        ),
        migrations.AddIndex(
            model_name='subprocess',
            index=models.Index(fields=['plant', 'is_active'], name='proc_subprocess_plant_act_idx'),
        ),
    ]
