# Generated by Django 5.2.17 on 2026-09-21 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_list_filter_indexes'),
        ('processes', '0002_list_filter_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='use_labor_properties',
            field=models.BooleanField(default=False, help_text='If enabled, quote can pick a labor role and auto-fill mapped process fields.'),
        ),
        migrations.AddField(
            model_name='process',
            name='use_machine_properties',
            field=models.BooleanField(default=False, help_text='If enabled, quote can pick a machine and auto-fill mapped process fields.'),
        ),
        migrations.AddField(
            model_name='processfield',
            name='labor_property_key',
            field=models.SlugField(blank=True, default='', help_text='Optional. e.g. hourly_rate or a labor custom field key.', max_length=80),
        ),
        migrations.AddField(
            model_name='processfield',
            name='machine_property_key',
            field=models.SlugField(blank=True, default='', help_text='Optional. e.g. hourly_rate or a machine custom field key.', max_length=80),
        ),
        migrations.AddField(
            model_name='quoteprocess',
            name='labor_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_processes', to='catalog.laborrole'),
        ),
        migrations.AddField(
            model_name='quoteprocess',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_processes', to='catalog.machine'),
        ),
        migrations.AddField(
            model_name='subprocess',
            name='use_labor_properties',
            field=models.BooleanField(default=False, help_text='If enabled, inherits labor context from the parent quote process when available.'),
        ),
        migrations.AddField(
            model_name='subprocess',
            name='use_machine_properties',
            field=models.BooleanField(default=False, help_text='If enabled, inherits machine context from the parent quote process when available.'),
        ),
        migrations.AddField(
            model_name='subprocessfield',
            name='labor_property_key',
            field=models.SlugField(blank=True, default='', help_text='Optional. e.g. hourly_rate or a labor custom field key.', max_length=80),
        ),
        migrations.AddField(
            model_name='subprocessfield',
            name='machine_property_key',
            field=models.SlugField(blank=True, default='', help_text='Optional. e.g. hourly_rate or a machine custom field key.', max_length=80),
        ),
        migrations.AlterField(
            model_name='process',
            name='use_material_properties',
            field=models.BooleanField(default=False, help_text='If enabled, quote can pick a material and auto-fill mapped process fields.'),
        ),
    ]
