# Generated by Django 5.1.7 on 2026-09-15 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('templates_engine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('company', models.CharField(blank=True, default='', max_length=200)),
                ('address_line1', models.CharField(blank=True, default='', max_length=255)),
                ('address_line2', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('postal_code', models.CharField(blank=True, default='', max_length=30)),
                ('country', models.CharField(blank=True, default='India', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=40, unique=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CALCULATED', 'Calculated'), ('ISSUED', 'Issued')], default='DRAFT', max_length=20)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='quotes.customer')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='core.plant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteCalculationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calculation', to='quotes.quote')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='quotes/pdfs/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('file_hash', models.CharField(blank=True, default='', max_length=64)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='quotes.quote')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('quantity', models.DecimalField(decimal_places=4, default=1, max_digits=14)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='quotes.quote')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quote_lines', to='templates_engine.producttemplate')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuoteLineParameterValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_code', models.SlugField()),
                ('value', models.CharField(max_length=200)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_values', to='quotes.quoteline')),
            ],
            options={
                'unique_together': {('line', 'parameter_code')},
            },
        ),
    ]
