# Generated by Django 5.2.17 on 2026-09-19 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_quote_customer_set_null'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-created_at', '-id']},
        ),
    ]
