# Generated by Django 5.2.17 on 2026-09-20 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('quotes', '0004_alter_customer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='weight_calc_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='quote',
            name='weight_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weight_quotes', to='catalog.material'),
        ),
        migrations.AddField(
            model_name='quote',
            name='weight_shape',
            field=models.SlugField(blank=True, default='', max_length=40),
        ),
    ]
