# Generated by Django 5.1.7 on 2026-09-15 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('MATERIAL', 'Material'), ('MACHINE', 'Machine'), ('LABOR', 'Labor'), ('QUOTE_INPUT', 'Quote Input'), ('PRODUCT_PARAMETER', 'Product Parameter')], max_length=30)),
                ('key', models.SlugField(max_length=80)),
                ('label', models.CharField(max_length=200)),
                ('data_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('bool', 'Boolean'), ('date', 'Date'), ('enum', 'Enum')], default='text', max_length=20)),
                ('enum_choices', models.JSONField(blank=True, default=list)),
                ('is_required', models.BooleanField(default=False)),
                ('is_importable', models.BooleanField(default=True)),
                ('import_column_header', models.CharField(blank=True, max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='core.plant')),
            ],
            options={
                'ordering': ['sort_order', 'key'],
                'unique_together': {('plant', 'entity_type', 'key')},
            },
        ),
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('value_text', models.TextField(blank=True, default='')),
                ('value_number', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('value_bool', models.BooleanField(blank=True, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='catalog.customfielddefinition')),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='catalog_cus_content_992ba7_idx')],
                'unique_together': {('definition', 'content_type', 'object_id')},
            },
        ),
        migrations.CreateModel(
            name='LaborRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('hourly_rate', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_roles', to='core.plant')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('plant', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('hourly_rate', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('setup_rate', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('efficiency_percent', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='core.plant')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('plant', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('uom', models.CharField(default='kg', max_length=30)),
                ('density', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('unit_price', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='core.plant')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('plant', 'code')},
            },
        ),
    ]
