# Generated by Django 5.2.17 on 2026-09-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customfielddefinition',
            index=models.Index(fields=['entity_type', 'is_active'], name='catalog_cfdef_ent_act_idx'),
        ),
        migrations.AddIndex(
            model_name='laborrole',
            index=models.Index(fields=['is_active'], name='catalog_labor_is_active_idx'),
        ),
        migrations.AddIndex(
            model_name='laborrole',
            index=models.Index(fields=['plant', 'is_active'], name='catalog_labor_plant_active_idx'),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['is_active'], name='catalog_mach_is_active_idx'),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['plant', 'is_active'], name='catalog_mach_plant_active_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['is_active'], name='catalog_mat_is_active_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['plant', 'is_active'], name='catalog_mat_plant_active_idx'),
        ),
    ]
